name: guatini
description: App for Guatini Project
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 3.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  flutter_native_splash: ^2.2.8
  adaptive_theme: ^3.2.0
  card_swiper: ^2.0.4
  selectable: ^0.2.9
  provider: ^6.0.3
  path_provider: ^2.0.11
  external_path: ^1.0.1
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  sqflite: ^2.0.3+1
  photo_view:
    path: packages/photo_view
  audioplayers: ^1.0.1
  video_player: ^2.4.6
  video_thumbnail: ^0.5.2
  geolocator: ^9.0.2
  mapsforge_flutter: ^2.0.2
  flutter_map: ^2.2.0
  qr_code_scanner: ^1.0.1
  url_launcher: any
  pdf: ^3.8.4
  dio: ^4.0.6
  version: ^3.0.2
  device_info_plus: ^8.1.0
  package_info_plus: ^3.0.3
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  app_dev_config: ^0.0.5
  dcdg: ^4.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/map_resources/

app_dev_config:
  launcher_name: Guatiní
  permissions:
    - internet
    - read_external_storage
    - write_external_storage
  android:
    apply: true
    compile_sdk: 33
    min_sdk: 21
    target_sdk: 29

flutter_icons:
  image_path: "assets/icons/android_icon.png"
  android: true
  image_path_android: "assets/icons/android_icon.png"
  adaptive_icon_foreground: "assets/icons/android_adaptative_icon_fg.png"
  adaptive_icon_background: "assets/icons/android_adaptative_icon_bg.png"
  ios: true
  image_path_ios: "assets/icons/ios_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: "assets/icons/android_icon.png"
  android: true
  ios: true
