name: Build application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  flutter_analize:
    name: Flutter analize
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: "14.x"

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Check Flutter version
        run: flutter --version

      - name: Analyze project source
        run: flutter analyze

  build_apk:
    name: Build APK
    needs: [flutter_analize]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@main
        
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +%Y/%m/%d - %H:%M:%S')"

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: "14.x"

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: app-release ${{ steps.date.outputs.date }}.apk
          path: build/app/outputs/apk/release/app-release.apk
