name: Build application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  flutter_analyze:
    name: Analyze code
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Install Java
        uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: "14.x"

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Check Flutter version
        run: flutter --version

  build_apk:
    name: Build APK
    needs: [flutter_analyze]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@main
        
      - name: Get current date and time
        id: datetime
        run: echo "builddate=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Install Java
        uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: "14.x"

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build app
        run: flutter build apk --release

      - name: Create Release Tag
        uses: ncipollo/release-action@main
        with:
         artifacts: "build/app/outputs/apk/release/app-release.apk"
         tag: ${{ steps.datetime.outputs.builddate }}
       
