name: Build application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  flutter_analize:
    name: Flutter analize
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: "14.x"

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Check Flutter version
        run: flutter --version

      - name: Analyze project source
        run: flutter analyze

  build_apk:
    name: Build APK
    needs: [flutter_analize]
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@main
        
      - name: Get current date and time
        id: datetime
        run: echo "builddate=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: "zulu"
          java-version: "14.x"

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --release
        
      - name: Create Tag
        uses: rickstaa/action-create-tag@main
        with:
          tag: ${{ steps.datetime.outputs.builddate }}

#       - name: Create Release
#         uses: ncipollo/release-action@main
#         with:
#          artifacts: "build/app/outputs/apk/release/app-release.apk"
#          tag: ${{ steps.datetime.outputs.builddate }}
       
