name: Build application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@main

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: "14.x"

      - name: Install Flutter
        uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --release
